version: '3.4'

services: 
  web:
    restart: always
    build: .
    expose:
      - "80"
    networks:
      - dev
    depends_on: 
      - db
  db:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - dev

volumes:
  pgdata:

networks:
  dev:
