version: '3.4'

services: 
  web:
    restart: always
    build: .
    expose:
      - "8100"
    networks:
      - dev
    depends_on: 
      - db
  db:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - dev
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      - dev

volumes:
  pgdata:

networks:
  dev:
