version: '3.4'

services: 
  db:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - pg_network
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - type: bind
        source: ./web/media
        target: /media
      - type: bind
        source: ./web/static
        target: /static
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
    networks:
      - nginx_network
    depends_on:
      - web
      - db
  web:
    restart: always
    build: .
    image: raumdeuter/slides:latest
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/uwsgi.conf
    volumes:
      - type: bind
        source: ./web
        target: /app
    networks:
      - nginx_network
      - pg_network
    depends_on:
      - db

volumes:
  pgdata:

networks:
  nginx_network:
    driver: bridge
  pg_network:
    driver: bridge

