version: '3.4'

services: 
  web:
    restart: always
    build: .
    expose:
      - "8100"
    depends_on: 
      - db
  db:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data/
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"

volumes:
  pgdata:
