# Generated by Django 2.2.9 on 2020-02-08 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001__initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagefile',
            name='file_hash',
        ),
        migrations.AddField(
            model_name='imagefile',
            name='anchor_x',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagefile',
            name='anchor_y',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagefile',
            name='length_x',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagefile',
            name='length_y',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagefile',
            name='datasource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classifier_classification_type', to='classifier.ClassificationType'),
            preserve_default=False,
        ),
    ]
